version: "3"
services:
  envoy:
    build: ./proxy
    ports:
      - "8080:8080"
    links:
      - "backend"

  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    ports:
      - "50051:50051"
    container_name: "backend"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
      - ./frontend/node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    links:
      - "backend"
